# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
bin = "/var/infinite/fleet"
cmd = "go build -o /var/infinite/fleet ./fleet.go"
delay = 1000
exclude_dir = [".git", "bin", "logs", "tmp", "vendor", "src/devUtils"]
follow_symlink = false
full_bin = "export $(grep -v '^#' .env | xargs); /var/infinite/fleet"
ignore = ["*_test.go", "testHelpers.go"]

[[watcher]]
build = true
watch = "src/**/*.go"
