# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
bin = "/var/speedia/control"
cmd = "make build"
exclude_dir = [".git", "bin", "logs", "tmp", "vendor", "src/devUtils"]
exclude_regex = [".*_templ.go"]
follow_symlink = false
ignore = ["*_test.go", "testHelpers.go"]
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
