basePath: /v1
definitions:
  dto.AddAccount:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.Login:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.UpdateAccount:
    properties:
      accountId:
        type: integer
      password:
        type: string
      shouldUpdateApiKey:
        type: boolean
    type: object
  entity.AccessToken:
    properties:
      expiresIn:
        type: integer
      tokenStr:
        type: string
      type:
        $ref: '#/definitions/valueObject.AccessTokenType'
    type: object
  entity.Account:
    properties:
      groupId:
        type: integer
      id:
        type: integer
      username:
        type: string
    type: object
  entity.O11yOverview:
    properties:
      currentUsage:
        $ref: '#/definitions/valueObject.CurrentResourceUsage'
      hostname:
        type: string
      publicIp:
        type: string
      specs:
        $ref: '#/definitions/valueObject.HardwareSpecs'
      uptimeSecs:
        type: integer
    type: object
  valueObject.AccessTokenType:
    enum:
    - sessionToken
    - accountApiKey
    type: string
    x-enum-varnames:
    - sessionToken
    - accountApiKey
  valueObject.CurrentResourceUsage:
    properties:
      cpuUsagePercent:
        type: number
      memUsagePercent:
        type: number
      netUsage:
        $ref: '#/definitions/valueObject.NetUsage'
      storageUsage:
        items:
          $ref: '#/definitions/valueObject.DiskInfo'
        type: array
    type: object
  valueObject.DiskInfo:
    properties:
      availableBytes:
        type: integer
      name:
        type: string
      totalBytes:
        type: integer
      usedBytes:
        type: integer
    type: object
  valueObject.HardwareSpecs:
    properties:
      cpuCores:
        type: integer
      cpuFrequency:
        type: number
      cpuModel:
        type: string
      memoryTotal:
        type: integer
      storageTotal:
        items:
          $ref: '#/definitions/valueObject.DiskInfo'
        type: array
    type: object
  valueObject.NetUsage:
    properties:
      receivedBytes:
        type: integer
      sentBytes:
        type: integer
    type: object
host: localhost:10001
info:
  contact:
    email: eng+swagger@speedia.net
    name: Speedia Engineering
    url: https://speedia.net/
  description: Speedia FleetManager API
  license:
    name: SPEEDIA WEB SERVICES © 2023. All Rights Reserved.
    url: https://speedia.net/tos/
  termsOfService: https://speedia.net/tos/
  title: SfmApi
  version: 0.0.1
paths:
  /account/:
    get:
      consumes:
      - application/json
      description: List accs.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Account'
            type: array
      security:
      - Bearer: []
      summary: GetAccounts
      tags:
      - account
    post:
      consumes:
      - application/json
      description: Add a new account.
      parameters:
      - description: NewAccount
        in: body
        name: addAccountDto
        required: true
        schema:
          $ref: '#/definitions/dto.AddAccount'
      produces:
      - application/json
      responses:
        "201":
          description: AccountCreated
          schema:
            type: object
      security:
      - Bearer: []
      summary: AddNewAccount
      tags:
      - account
    put:
      consumes:
      - application/json
      description: Update an account.
      parameters:
      - description: UpdateAccount
        in: body
        name: updateAccountDto
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: AccountUpdated message or NewKeyString
          schema:
            type: object
      security:
      - Bearer: []
      summary: UpdateAccount
      tags:
      - account
  /account/{accountId}/:
    delete:
      consumes:
      - application/json
      description: Delete an account.
      parameters:
      - description: AccountId
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: AccountDeleted
          schema:
            type: object
      security:
      - Bearer: []
      summary: DeleteAccount
      tags:
      - account
  /auth/login/:
    post:
      consumes:
      - application/json
      description: Generate JWT with credentials
      parameters:
      - description: Login
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AccessToken'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: GenerateJwtWithCredentials
      tags:
      - auth
  /o11y/overview/:
    get:
      consumes:
      - application/json
      description: Show system information and resource usage.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.O11yOverview'
      security:
      - Bearer: []
      summary: O11yOverview
      tags:
      - o11y
securityDefinitions:
  Bearer:
    description: Type "Bearer" + JWT token or API key.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
